/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    pages: Page;
    projects: Project;
    'cover-letters': CoverLetter;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'cover-letters': CoverLettersSelect<false> | CoverLettersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    cv: Cv;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    cv: CvSelect<false> | CvSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Modular pages built from blocks. Set slug to "home" for the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use "home" for the homepage.
   */
  slug: string;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            headline: string;
            intro?: string | null;
            media?: (number | null) | Media;
            cta?: {
              label?: string | null;
              href?: string | null;
              style?: ('primary' | 'secondary') | null;
            };
            secondaryCTA?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body: string;
            mediaType?: ('image' | 'video' | 'none') | null;
            media?: (number | null) | Media;
            videoUrl?: string | null;
            aspectRatio?: ('16/9' | '4/3' | '1/1' | '3/4') | null;
            layout?: ('media-right' | 'media-left') | null;
            caption?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
              style?: ('primary' | 'secondary') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textMedia';
          }
        | {
            quote: string;
            attribution?: string | null;
            context?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
              style?: ('primary' | 'secondary') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            intro?: string | null;
            /**
             * Leave empty to auto-select featured projects
             */
            projects?: (number | Project)[] | null;
            showAllLink?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProjects';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Portfolio projects with a structured summary and flexible content sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL slug, e.g. mobile-banking-relaunch
   */
  slug: string;
  client?: string | null;
  year?: string | null;
  role?: string | null;
  featured?: boolean | null;
  /**
   * Optional accent color used in the frontend card and detail page
   */
  accentColor?: string | null;
  excerpt: string;
  coverImage?: (number | null) | Media;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  challenge?: string | null;
  solution?: string | null;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            eyebrow?: string | null;
            title: string;
            body: string;
            layout?: ('media-right' | 'media-left' | 'text-only') | null;
            media?: (number | null) | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaHighlight';
          }
        | {
            title?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            quote: string;
            attribution?: string | null;
            context?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Per-application cover letters. Share the token URL with employers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cover-letters".
 */
export interface CoverLetter {
  id: number;
  token?: string | null;
  company: string;
  role: string;
  jobTitle?: string | null;
  shareDisabled?: boolean | null;
  shareExpiresAt?: string | null;
  recipientSalutation?: string | null;
  body?: string | null;
  closing?: string | null;
  senderName?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'cover-letters';
        value: number | CoverLetter;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              intro?: T;
              media?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textMedia?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              mediaType?: T;
              media?: T;
              videoUrl?: T;
              aspectRatio?: T;
              layout?: T;
              caption?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              context?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featuredProjects?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              projects?: T;
              showAllLink?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  year?: T;
  role?: T;
  featured?: T;
  accentColor?: T;
  excerpt?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  challenge?: T;
  solution?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        text?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        mediaHighlight?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              layout?: T;
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              context?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cover-letters_select".
 */
export interface CoverLettersSelect<T extends boolean = true> {
  token?: T;
  company?: T;
  role?: T;
  jobTitle?: T;
  shareDisabled?: T;
  shareExpiresAt?: T;
  recipientSalutation?: T;
  body?: T;
  closing?: T;
  senderName?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  navLogo?: (number | null) | Media;
  tagline?: string | null;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  contactButtonLabel?: string | null;
  /**
   * Links displayed in the footer (e.g. Impressum, Datenschutz, GitHub)
   */
  footerLinks?:
    | {
        label: string;
        type?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv".
 */
export interface Cv {
  id: number;
  name: string;
  title?: string | null;
  email?: string | null;
  phone?: string | null;
  location?: string | null;
  website?: string | null;
  linkedin?: string | null;
  profileImage?: (number | null) | Media;
  logo?: (number | null) | Media;
  summary?: string | null;
  experience?:
    | {
        duration?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        company?: string | null;
        role?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Maximum number of dots shown for each skill rating
   */
  skillMaxDots?: number | null;
  skills?:
    | {
        name?: string | null;
        /**
         * Number of filled dots
         */
        level?: number | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        name?: string | null;
        level?: string | null;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        institution?: string | null;
        degree?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  certificates?:
    | {
        name?: string | null;
        issuer?: string | null;
        date?: string | null;
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  navLogo?: T;
  tagline?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  contactButtonLabel?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv_select".
 */
export interface CvSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  email?: T;
  phone?: T;
  location?: T;
  website?: T;
  linkedin?: T;
  profileImage?: T;
  logo?: T;
  summary?: T;
  experience?:
    | T
    | {
        duration?: T;
        startDate?: T;
        endDate?: T;
        company?: T;
        role?: T;
        description?: T;
        id?: T;
      };
  skillMaxDots?: T;
  skills?:
    | T
    | {
        name?: T;
        level?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        name?: T;
        level?: T;
        id?: T;
      };
  education?:
    | T
    | {
        institution?: T;
        degree?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  certificates?:
    | T
    | {
        name?: T;
        issuer?: T;
        date?: T;
        status?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}